use customer_behaviour;
select * from customer limit 5;
#Q1. What is the total revenue generated by male vs. female customerd?
select gender, sum(purchase_amount) as revenue 
from customer 
group by gender;
#Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount from customer 
where discount_applied = 'yes' and purchase_amount >= (select avg(purchase_amount) from customer);
#Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, avg(review_rating) as avg_rating
from customer
group by item_purchased
order by avg_rating desc
limit 5;
#Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,
avg(purchase_amount)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;
#Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
avg(purchase_amount) as avg_spend,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by avg_spend desc, total_revenue desc;
#Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
(sum(case when discount_applied = 'yes' then 1 else 0 end) * 100.0 / count(*)) as discount_percentage
from customer
group by item_purchased
order by discount_percentage desc
limit 5;
#Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
select 
case
when previous_purchases = 0 then 'New'
when previous_purchases between 1 and 5 then 'Returning'
else 'Loyal'
end as customer_segment,
count(*) as customer_count
from customer
group by 
case
when previous_purchases = 0 then 'New'
when previous_purchases between 1 and 5 then 'Returning'
else 'Loyal'
end;
#Q8. What are the top 3 most purchased products within each category?
select category, item_purchased, total_purchases
from (
select category, 
item_purchased,
count(*) as total_purchases,
row_number() over (partition by category order by count(*) desc) as rn
from customer
group by category, item_purchased
) as ranked
where rn <= 3;
#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(*) as customer_count,
round(count(*) * 100.0 / (
select count(*)
from customer
where previous_purchases > 5), 2) as percentage
from customer
where previous_purchases > 5
group by subscription_status;
#Q10. What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;